-----------------SEKWENCJE-----------------
DROP SEQUENCE WYKLADOWCY_SEQ;
DROP SEQUENCE KIERUNKI_SEQ;
DROP SEQUENCE GRUPY_SEQ;
DROP SEQUENCE KURSY_SEQ;
DROP SEQUENCE BIBLIOTEKA_SEQ;
DROP SEQUENCE STUDENCI_SEQ;
DROP SEQUENCE STYPENDIA_SEQ;
DROP SEQUENCE PRZEDMIOTY_SEQ;

-----------------------------------------
CREATE SEQUENCE WYKLADOWCY_SEQ;
CREATE SEQUENCE KIERUNKI_SEQ;
CREATE SEQUENCE GRUPY_SEQ;
CREATE SEQUENCE KURSY_SEQ;
CREATE SEQUENCE BIBLIOTEKA_SEQ;
CREATE SEQUENCE STUDENCI_SEQ;
CREATE SEQUENCE STYPENDIA_SEQ;
CREATE SEQUENCE PRZEDMIOTY_SEQ;


